#PBS -l select=1:ncpus=10:mpiprocs=10:mem=109gb
#PBS -l walltime=06:00:00 
#PBS -N b_x16_main8_init
#PBS -o /glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io/build_out/build_out_qp_x16_init_rad_sep_48_latin_no_qrad
#PBS -e /glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io/build_out/build_err_qp_x16_init_rad_sep_48_latin_no_qrad
#PBS -q regular
#PBS -A UMIT0027

echo 'building data! qv_init correction'
cd '/glade/work/janniy/python_ncar_env/bin/'
source activate
cd '/glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io'
python < 'build_rf_simple_qp_16_with_sed_correction_48_init_x16_10_samp_in_leaf_no_qrad.py';
echo 'training RF! qv_init correction'
python < 'run_rf_simple_qp_16_with_sed_correction_48_init_x16_10_samp_in_leaf_no_qrad.py';

