#PBS -l select=1:ncpus=10:mpiprocs=10:mem=109gb
#PBS -l walltime=06:00:00 
#PBS -N b_tkz_x32_prod
#PBS -o /glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io/build_out/build_out_x32_tkz
#PBS -e /glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io/build_out/build_err_x32_tkz
#PBS -q regular
#PBS -A UMIT0027

echo 'building data! qv_init correction'
cd '/glade/work/janniy/python_ncar_env/bin/'
source activate
cd '/glade/u/home/janniy/convection_parametrization/paul_codes/ML-convection_sam_flex_io'
python < 'build_tkz_production_x32.py' 
echo 'training RF! qv_init correction'
python < 'run_tkz_production_x32.py'

